# Escolhando a imagem base
FROM node:14.16-alpine

# Informando diretorio de trabalho
WORKDIR /app

ENV VUE_APP_BACKEND_API=http://localhost
# Adicionando variaveis de ambiente necessarias
#ENV PATH /app/node_modules/.bin:$PATH

# Instalando as dependencias do projeto
COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .

EXPOSE 8080
EXPOSE 49153

CMD ["npm", "run", "serve"]
#ENTRYPOINT ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]