FROM node:14.16-alpine as build

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .

ENV VUE_APP_BACKEND_API=http://ip172-18-0-52-c1bq9t3e75e000ar0vu0-80.direct.labs.play-with-docker.com

RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./.nginx/nginx-prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
