# Escolhando a imagem base
FROM node:14.16-alpine

# Informando diretorio de trabalho
WORKDIR /app

# Adicionando variaveis de ambiente necessarias
#ENV PATH /app/node_modules/.bin:$PATH

# Instalando as dependencias do projeto
COPY package.json .
COPY package-lock.json .
RUN npm install
RUN npm install -g @angular/cli

COPY . .

EXPOSE 4200
EXPOSE 49153

CMD ["npm", "start"]
#ENTRYPOINT ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]