FROM node:14.16-alpine as build

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .

ARG env=prod
RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist/covid-curch /usr/share/nginx/html
COPY ./.nginx/nginx-prod.conf /etc/nginx/conf.d/default.conf