version: "3.7"

services:

  frontend:
    image: fcrodrigues/vuejs-frontend-prod:latest
    ports: 
      - 80:80
    depends_on:
      - web

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  
  web:
    image: fcrodrigues/python-api:latest
    ports:
      - "8001:8000"
    depends_on:
      - db

  